### ISSUE TITLE
fitsio install inconsistencies

### ISSUE THREAD

**Issue by bshapiroalbert** [PsrSigSim/VersionZeroPointZero#152]
The fitsio install (at least on ubuntu 20.04, fresh install, using conda) has inconsistent requirements that may cause the psrsigsim install to fail. pdat requires fitsio>=0.9.10, but the psrsigsim must use fitsio==0.9.12 (at least right now), and if pdat is not preinstalled this causes the install to fail (@Hazboun6 may need/want to update this as well since I think pdat will also actually require fitsio 0.9.12). We need to have some documentation somewhere that goes over how to do this.

 I was able to successfully install the psrsigim on a fresh ubuntu 20.04 using anaconda with the following steps:
0. Make sure a C-compiler is installed, e.g. run: `sudo apt-get install build-essential`, check with `which gcc`
1. install conda for linux
2. create a new conda environment with python 3.7, numpy, scipy, astropy, matplotlib
3. install fitsio separately with: `pip install fitsio==0.9.12`
(Theoretically one should be able to just `pip install psrsigsim` now, but I also installed `pdat` and `pint` separately)
4. pip install git+git.psrsigsim.....

Which works fine. I know others have this issue, so we should document this somewhere, maybe the readme?

**Comment by paulthebaker** [comment]
If you don't preinstall `fitsio` at a fixed version, which version does `pdat` install?

**Comment by Hazboun6** [comment]
@paulthebaker I have now [changed](https://github.com/Hazboun6/PulsarDataToolbox/commit/155d07c021a471790a0425946fd59e6d665031a5) `pdat` so that when it is pip installed it will automatically install `fitsio==0.9.12`.   I've run the PsrSigSim tests, local tests and @bshapiroalbert has also tested this locally. I think we've accomplished an appropriate workaround, though of course `pdat` itself could use some more work.

**Comment by bshapiroalbert** [comment]
Ditto what @Hazboun6 said. I think we can probably close this issue now unless there's anything else we should discuss regarding this now.
