### ISSUE TITLE
Paper Review

### ISSUE THREAD

**Issue by JBorrow** [PsrSigSim/VersionZeroPointZero#160]
I only have two short comments on the JOSS paper that you have submitted:

1. The citation `[Shapiro-Albert, 2020]` should not have those square brackets - I think you mean to use `@PaperYear` (i.e. not `[@PaperYear]` as used for the 'regular' bracketed citations).

2. I would like to see a short review of the state of the field, with a focus on answering the following two questions:
  a. Is `PsrSigSim` the first software package of its kind? If not, list other competing packages.
  b. What is particularly novel about `PsrSigSim`? This could be anything from the inclusion of new functionality relative to other packages, or just the fact that it has a nice object-oriented interface.

Other than this, the paper looks good to me, especially considering this will be combined with an ApJ publication.

This issue is part of my JOSS review.

**Comment by Hazboun6** [comment]
@JBorrow This citation is a place holder for the AAS paper. In AAS-style guidelines they ask that you write in prep work directly into the paper, rather than add a separate citation. I suppose I should just ask the JOSS folks what the best option is for this. 

A state of the field review is a great idea! There is at least one other package in `c`, but nothing in Python.

**Comment by Hazboun6** [comment]
@JBorrow  I have made the suggested changes to the paper and I've now replaced the Shapiro-Albert reference with the arxiv version of the ApJ paper.
